### ISSUE TITLE
Datenbankauszug

### ISSUE THREAD

**Issue by Lightshadow244** [AchMenz/EasyOrderBL#14]
Text generien aus Datenbank. 
Alles wo Anzahl größer 0 soll in die Bestellung.

**Comment by Lightshadow244** [comment]
Es soll ein Klasse geben die alles in Attribute steckt und eine Funktion die dann den Text herausgibt

**Comment by AchMenz** [comment]
Diese Klasse wurde geschrieben. Sie befindet sich in views.py und heißt "PrintOrder".
